### ISSUE TITLE
Typo in GitHub URL for "messageMe" Project on Portfolio Page

### ISSUE THREAD

**Issue by KnotzerIO** [JuliaShlykova/portfolio#1]
Hey Julia, your portfolio is quite impressive, but I encountered an issue while exploring your projects. There's a minor issue with the GitHub URL for the "messageMe" project listed on your portfolio. The current URL points to a non-existent repository and seems to be a typo.

**Current URL:**
```plaintext
https://github.com/JuliaShlykova/messaging-app-frontends
```

**Correct URL (Assumed):**
```plaintext
https://github.com/JuliaShlykova/messaging-app-frontend
```

**Relevant Portfolio Snippet:**
```javascript
// src/components/project-list.js
{
  name: "messageMe", 
  description: "MERN-stack website. A chat application with the feature of real-time message exchange, online users and creation of group chats",
  screenshot: messageMe,
  githubUrl: "https://github.com/JuliaShlykova/messaging-app-frontends", // Typo here
  url: "https://messaging-app-frontend-two.vercel.app/",
  languages: [mongodb, reactjs, node]
}
```

Adjusting the `githubUrl` value to the correct link would help visitors explore the "messageMe" project directly from your portfolio.

Thanks for sharing your projects, and looking forward to seeing this minor issue resolved!

**Comment by JuliaShlykova** [comment]
Thank you so much for noticing!
